<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Stride.CommunityToolkit" Version="1.0.0-preview.56" />
    <PackageReference Include="Stride.CommunityToolkit.Bepu" Version="1.0.0-preview.56" />
    <PackageReference Include="Stride.CommunityToolkit.Skyboxes" Version="1.0.0-preview.56" />
    <PackageReference Include="Stride.CommunityToolkit.Windows" Version="1.0.0-preview.56" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.1.0" />    
  </ItemGroup>

</Project>
